### ISSUE TITLE
VCFs as input

### ISSUE THREAD

**Issue by GaloGS** [microbial-pangenomes-lab/microGWAS#39]
Hello! 

In first place, thank you very much for this tool. I am a pyseer user and this pipeline seems superuseful!

I was wondering whether a potential improvement for the pipeline would be to allow starting from annotated VCFs. In _M. tuberculosis_ 
/we rarely use assemblies :(

**Comment by mgalardini** [comment]
Hi, thanks for your interest; we are thinking about your question (which does not have an obvious immediate fix), and will try to have an answer for you in the coming days

**Comment by mgalardini** [comment]
Hi, we have thought about potentially allowing a direct VCF input, but unfortunately it would require to restructure the pipeline completely, since so much of it depends on the assumption of the user providing annotated genome assemblies. If you were to convert your VCF to separate assemblies (fasta + GFF, with unique locus tags for each isolate), then you would be able to use the pipeline. But it might not be ideal. On the plus side if you have a VCF ready you can simply use a tool like pyseer and don't really "need" our pipeline to prepare the data...
